package com.survisha.meghaconnect.dto;

import com.survisha.meghaconnect.entity.Appointment;
import lombok.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class AppointmentDto {
    private Long id;
    private String applicationId;
    private Long applicantId;
    private VisitorDto applicant;
    private String applicantName;
    private String applicantPhone;
    private Long departmentId;
    private String departmentCode;
    private String departmentName;
    private Appointment.EventType eventType;
    private String subject;
    private String department;
    private String appointmentType;
    private String appointmentSource;
    private String guestReferenceId;
    private String guestName;
    private String guestMobile;
    private String guestAddress;
    private String guestEmail;
    private String organizationName;
    private String guestDesignation;
    private String visitorCategory;
    private String referredOffice;
    private String referredByName;
    private String reasonForAppointment;
    private LocalDate preferredDate;
    private Boolean consentAccepted;
    private String consentVersion;
    private String consentTimestamp;
    private String privacyPolicyUrl;
    private String termsUrl;
    private String agendaType;
    private String agendaBrief;
    private Appointment.AppointmentStatus status;
    private Appointment.AppointmentCategory appointmentCategory;
    private Appointment.MeetingLocation requestedLocation;
    private LocalDateTime scheduledDateTime;
    private Integer scheduledDurationMinutes;
    private Boolean mlaMdcApproved;
    private String cmoRemarks;
    private String approverRemarks;
    private String hcmRemarks;
    private String shortNotes;
    private Long routedDepartmentId;
    private String routedDepartmentName;
    private String routedOfficer;
    private String returnReason;
    private String requiredInformation;
    private LocalDate returnDueDate;
    private String meetingOutcome;
    private LocalDateTime completedAt;
    private String completedBy;
    private Boolean followUpRequired;
    private Boolean isWalkIn;
    private String walkInTokenNumber;
    private Integer meetingCountLast6Months;
    private List<AssociateVisitorDto> associates;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
