-- V34__insert_department_reference_data.sql
-- Seed Meghalaya government departments as reference data for scheme allocation and follow-up tagging.

INSERT IGNORE INTO reference_type (code, name, description, status) VALUES
('DEPARTMENT', 'Departments', 'Meghalaya government departments for scheme allocation and follow-up', 'ACTIVE');

INSERT IGNORE INTO reference_data (type_id, code, value, display_order, is_active)
VALUES
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'AGRICULTURE_FARMERS_WELFARE', 'Agriculture and Farmers Welfare Department', 1, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'ANIMAL_HUSBANDRY_VETERINARY', 'Animal Husbandry and Veterinary Department', 2, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'ARTS_CULTURE', 'Arts and Culture Department', 3, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'BORDER_AREAS_DEVELOPMENT', 'Border Areas Development Department', 4, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'CABINET_AFFAIRS', 'Cabinet Affairs Department', 5, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'COMMERCE_INDUSTRIES', 'Commerce and Industries Department', 6, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'COMMUNITY_RURAL_DEVELOPMENT', 'Community and Rural Development Department', 7, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'COOPERATION', 'Cooperation Department', 8, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'DISTRICT_COUNCIL_AFFAIRS', 'District Council Affairs Department', 9, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'EDUCATION', 'Education Department', 10, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'ELECTIONS', 'Elections Department', 11, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'EXCISE_REG_TAX_STAMPS', 'Excise Registration Taxation and Stamps Department', 12, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'FINANCE', 'Finance Department', 13, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'FISHERIES', 'Fisheries Department', 14, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'FOOD_CIVIL_SUPPLIES_CONSUMER_AFFAIRS', 'Food Civil Supplies and Consumer Affairs Department', 15, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'FOREST_ENVIRONMENT', 'Forest and Environment Department', 16, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'GENERAL_ADMINISTRATION', 'General Administration Department', 17, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'HEALTH_FAMILY_WELFARE', 'Health and Family Welfare Department', 18, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'HOME_POLICE', 'Home Police Department', 19, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'HOME_CIVIL_DEFENCE_HOME_GUARDS', 'Home Civil Defence and Home Guards Department', 20, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'HOME_PASSPORT', 'Home Passport Department', 21, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'HOME_POLITICAL', 'Home Political Department', 22, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'HOUSING', 'Housing Department', 23, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'INFORMATION_TECH_COMMUNICATION', 'Information Technology and Communication Department', 24, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'INFORMATION_PUBLIC_RELATIONS', 'Information and Public Relations Department', 25, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'LABOUR_EMPLOYMENT_SKILL_DEV', 'Labour Employment and Skill Development Department', 26, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'LAW', 'Law Department', 27, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'LEGAL_METROLOGY', 'Legal Metrology Department', 28, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'MINING_GEOLOGY', 'Mining and Geology Department', 29, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'PERSONNEL_ADMIN_REFORMS', 'Personnel and Administrative Reforms Department', 30, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'PLANNING_INVESTMENT_SUSTAINABLE_DEV', 'Planning Investment Promotion and Sustainable Development Department', 31, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'POWER', 'Power Department', 32, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'PRINTING_STATIONERY', 'Printing and Stationery Department', 33, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'PRISONS_CORRECTIONAL_SERVICES', 'Prisons and Correctional Services Department', 34, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'PUBLIC_HEALTH_ENGINEERING', 'Public Health Engineering Department', 35, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'PUBLIC_WORKS', 'Public Works Department', 36, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'REGISTRATION', 'Registration Department', 37, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'REVENUE_DISASTER_MANAGEMENT', 'Revenue and Disaster Management Department', 38, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'SCIENCE_TECHNOLOGY', 'Science and Technology Department', 39, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'SERICULTURE_WEAVING', 'Sericulture and Weaving Department', 40, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'SOCIAL_WELFARE', 'Social Welfare Department', 41, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'SPORTS_YOUTH_AFFAIRS', 'Sports and Youth Affairs Department', 42, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'TOURISM', 'Tourism Department', 43, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'TRANSPORT', 'Transport Department', 44, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'URBAN_AFFAIRS', 'Urban Affairs Department', 45, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'WATER_RESOURCES', 'Water Resources Department', 46, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'SOIL_WATER_CONSERVATION', 'Soil and Water Conservation Department', 47, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'LEGISLATIVE_ASSEMBLY_SECRETARIAT', 'Meghalaya Legislative Assembly Secretariat', 48, TRUE),
((SELECT id FROM reference_type WHERE code = 'DEPARTMENT'), 'SECRETARIAT_ADMINISTRATION', 'Meghalaya Secretariat Administration Department', 49, TRUE);
