CREATE TABLE appointment_qr_token (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    appointment_id  BIGINT       NOT NULL,
    visitor_id      BIGINT       NOT NULL,
    token_hash      VARCHAR(64)  NOT NULL,
    status          VARCHAR(30)  NOT NULL,
    valid_from      DATETIME     NOT NULL,
    valid_to        DATETIME     NOT NULL,
    generated_by    VARCHAR(100) NOT NULL,
    generated_at    DATETIME     NOT NULL,
    checked_in_at   DATETIME,
    checked_in_by   VARCHAR(100),
    checked_out_at  DATETIME,
    checked_out_by  VARCHAR(100),
    revoked_at      DATETIME,
    revoked_by      VARCHAR(100),
    gate_name       VARCHAR(150),
    device_id       VARCHAR(150),
    PRIMARY KEY (id),
    UNIQUE KEY uq_appointment_qr_token_hash (token_hash),
    KEY idx_qr_token_appointment (appointment_id),
    KEY idx_qr_token_visitor (visitor_id),
    KEY idx_qr_token_status_validity (status, valid_from, valid_to),
    CONSTRAINT fk_qr_token_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id),
    CONSTRAINT fk_qr_token_visitor FOREIGN KEY (visitor_id) REFERENCES visitors(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE qr_scan_audit_log (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    token_hash      VARCHAR(64)  NOT NULL,
    appointment_id  BIGINT,
    visitor_id      BIGINT,
    scanned_by      VARCHAR(100) NOT NULL,
    device_id       VARCHAR(150),
    gate_name       VARCHAR(150),
    action          VARCHAR(30)  NOT NULL,
    status          VARCHAR(20)  NOT NULL,
    failure_reason  VARCHAR(500),
    ip_address      VARCHAR(100),
    user_agent      VARCHAR(500),
    request_id      VARCHAR(128),
    created_at      DATETIME     NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qr_scan_audit_created_at (created_at),
    KEY idx_qr_scan_audit_request_id (request_id),
    KEY idx_qr_scan_audit_status_action (status, action),
    KEY idx_qr_scan_audit_gate (gate_name),
    KEY idx_qr_scan_audit_appointment (appointment_id),
    KEY idx_qr_scan_audit_visitor (visitor_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE visitor_movement_log (
    id              BIGINT       NOT NULL AUTO_INCREMENT,
    appointment_id  BIGINT       NOT NULL,
    visitor_id      BIGINT       NOT NULL,
    movement_type   VARCHAR(20)  NOT NULL,
    scanned_by      VARCHAR(100) NOT NULL,
    gate_name       VARCHAR(150),
    device_id       VARCHAR(150),
    scan_time       DATETIME     NOT NULL,
    remarks         VARCHAR(500),
    PRIMARY KEY (id),
    KEY idx_visitor_movement_scan_time (scan_time),
    KEY idx_visitor_movement_gate (gate_name),
    KEY idx_visitor_movement_type (movement_type),
    KEY idx_visitor_movement_appointment (appointment_id),
    KEY idx_visitor_movement_visitor (visitor_id),
    CONSTRAINT fk_movement_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id),
    CONSTRAINT fk_movement_visitor FOREIGN KEY (visitor_id) REFERENCES visitors(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
