ALTER TABLE reference_data
    ADD COLUMN parent_id BIGINT NULL AFTER type_id,
    ADD CONSTRAINT fk_reference_data_parent FOREIGN KEY (parent_id) REFERENCES reference_data(id),
    ADD INDEX idx_reference_data_parent (parent_id);

INSERT INTO reference_type (code, name, description, status)
SELECT 'MEGHALAYA_DISTRICT', 'Meghalaya District', 'Districts of Meghalaya', 'ACTIVE'
WHERE NOT EXISTS (SELECT 1 FROM reference_type WHERE code = 'MEGHALAYA_DISTRICT');

INSERT INTO reference_type (code, name, description, status)
SELECT 'MEGHALAYA_DISTRICT_MANDAL', 'Meghalaya District Mandal',
       'Mandal/constituency values mapped to Meghalaya districts', 'ACTIVE'
WHERE NOT EXISTS (SELECT 1 FROM reference_type WHERE code = 'MEGHALAYA_DISTRICT_MANDAL');

INSERT INTO reference_data (type_id, code, value, display_order, is_active)
SELECT rt.id, seed.code, seed.value, seed.ord, TRUE
FROM reference_type rt
JOIN (
 SELECT 'S1505' code, 'EAST GARO HILLS' value, 1 ord UNION ALL SELECT 'S1508','EAST JAINTIA HILLS',2 UNION ALL
 SELECT 'S1503','EAST KHASI HILLS',3 UNION ALL SELECT 'S1512','EASTERN WEST KHASI HILLS',4 UNION ALL
 SELECT 'S1510','NORTH GARO HILLS',5 UNION ALL SELECT 'S1502','RI-BHOI',6 UNION ALL
 SELECT 'S1507','SOUTH GARO HILLS',7 UNION ALL SELECT 'S1511','SOUTH WEST GARO HILLS',8 UNION ALL
 SELECT 'S1509','SOUTH WEST KHASI HILLS',9 UNION ALL SELECT 'S1506','WEST GARO HILLS',10 UNION ALL
 SELECT 'S1501','WEST JAINTIA HILLS',11 UNION ALL SELECT 'S1504','WEST KHASI HILLS',12
) seed
WHERE rt.code='MEGHALAYA_DISTRICT'
  AND NOT EXISTS (SELECT 1 FROM reference_data rd WHERE rd.type_id=rt.id AND rd.code=seed.code);

INSERT INTO reference_data (type_id, parent_id, code, value, display_order, is_active)
SELECT mrt.id, district.id, seed.code, seed.value, seed.ord, TRUE
FROM reference_type mrt
JOIN (
 SELECT 'S1505' district_code,'42' code,'RONGJENG' value,1 ord UNION ALL SELECT 'S1505','41','SONGSAK',2 UNION ALL SELECT 'S1505','43','WILLIAM NAGAR',3 UNION ALL
 SELECT 'S1508','6','KHLIEHRIAT',1 UNION ALL SELECT 'S1508','5','SUTNGA SAIPUNG',2 UNION ALL
 SELECT 'S1503','29','MAWKYNREW',1 UNION ALL SELECT 'S1503','15','MAWLAI',2 UNION ALL SELECT 'S1503','24','MAWPHLANG',3 UNION ALL SELECT 'S1503','13','MAWRYNGKNENG',4 UNION ALL SELECT 'S1503','25','MAWSYNRAM',5 UNION ALL SELECT 'S1503','20','MYLLIEM',6 UNION ALL SELECT 'S1503','22','NONGKREM',7 UNION ALL SELECT 'S1503','21','NONGTHYMMAI',8 UNION ALL SELECT 'S1503','17','NORTH SHILLONG',9 UNION ALL SELECT 'S1503','14','PYNTHORUMKHRAH',10 UNION ALL SELECT 'S1503','27','PYNURSLA',11 UNION ALL SELECT 'S1503','26','SHELLA',12 UNION ALL SELECT 'S1503','23','SOHIONG',13 UNION ALL SELECT 'S1503','28','SOHRA',14 UNION ALL SELECT 'S1503','19','SOUTH SHILLONG',15 UNION ALL SELECT 'S1503','18','WEST SHILLONG',16 UNION ALL
 SELECT 'S1512','31','MAWTHADRAISHAN',1 UNION ALL
 SELECT 'S1510','37','KHARKUTTA',1 UNION ALL SELECT 'S1510','38','MENDIPATHAR',2 UNION ALL SELECT 'S1510','39','RESUBELPARA',3 UNION ALL
 SELECT 'S1502','8','MAWHATI',1 UNION ALL SELECT 'S1502','9','NONGPOH',2 UNION ALL SELECT 'S1502','12','UMROI',3 UNION ALL SELECT 'S1502','11','UMSNING',4 UNION ALL
 SELECT 'S1507','59','CHOKPOT',1 UNION ALL SELECT 'S1507','58','RONGARA SIJU',2 UNION ALL
 SELECT 'S1511','54','MAHENDRAGANJ',1 UNION ALL SELECT 'S1511','55','SALMANPARA',2 UNION ALL
 SELECT 'S1509','35','RANIKOR',1 UNION ALL
 SELECT 'S1506','57','DALU',1 UNION ALL SELECT 'S1506','56','GAMBEGRE',2 UNION ALL SELECT 'S1506','50','NORTH TURA',3 UNION ALL SELECT 'S1506','46','PHULBARI',4 UNION ALL SELECT 'S1506','47','RAJABALA',5 UNION ALL SELECT 'S1506','44','RAKSAMGRE',6 UNION ALL SELECT 'S1506','52','RANGSAKONA',7 UNION ALL SELECT 'S1506','48','SELSELLA',8 UNION ALL SELECT 'S1506','51','SOUTH TURA',9 UNION ALL SELECT 'S1506','45','TIKRIKILLA',10 UNION ALL
 SELECT 'S1501','2','JOWAI',1 UNION ALL SELECT 'S1501','4','MOWKAIAW',2 UNION ALL SELECT 'S1501','1','NARTIANG',3 UNION ALL SELECT 'S1501','3','RALIANG',4 UNION ALL
 SELECT 'S1504','32','NONGSTOIN',1 UNION ALL SELECT 'S1504','33','RAMBRAI JYRNGAM',2
) seed
JOIN reference_type drt ON drt.code='MEGHALAYA_DISTRICT'
JOIN reference_data district ON district.type_id=drt.id AND district.code=seed.district_code
WHERE mrt.code='MEGHALAYA_DISTRICT_MANDAL'
  AND NOT EXISTS (SELECT 1 FROM reference_data rd WHERE rd.type_id=mrt.id AND rd.code=seed.code);
