CREATE TABLE IF NOT EXISTS direction_follow_ups (
    id BIGINT NOT NULL AUTO_INCREMENT,
    direction_id VARCHAR(30) NULL,
    appointment_id BIGINT NOT NULL,
    visitor_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    responsible_officer_name VARCHAR(200) NULL,
    instruction TEXT NOT NULL,
    due_date DATE NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    evidence_required BOOLEAN NOT NULL DEFAULT FALSE,
    last_escalated_at DATETIME NULL,
    completed_date DATETIME NULL,
    completion_remarks TEXT NULL,
    created_by VARCHAR(100) NULL,
    updated_by VARCHAR(100) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_direction_follow_up_direction_id (direction_id),
    KEY idx_followup_department_status_due (department_id, status, due_date),
    KEY idx_followup_appointment (appointment_id),
    KEY idx_followup_visitor (visitor_id),
    CONSTRAINT fk_followup_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id),
    CONSTRAINT fk_followup_visitor FOREIGN KEY (visitor_id) REFERENCES visitors(id),
    CONSTRAINT fk_followup_department FOREIGN KEY (department_id) REFERENCES departments(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
