CREATE TABLE voice_remarks (
    id BIGINT NOT NULL AUTO_INCREMENT,
    request_id VARCHAR(64) NOT NULL,
    reference_type VARCHAR(40) NOT NULL,
    reference_id VARCHAR(100) NOT NULL,
    audio_file_path VARCHAR(1000) NOT NULL,
    audio_file_name VARCHAR(255) NOT NULL,
    original_file_name VARCHAR(255) NULL,
    audio_format VARCHAR(30) NOT NULL,
    audio_duration_ms BIGINT NULL,
    audio_size_bytes BIGINT NOT NULL,
    recorded_by VARCHAR(255) NOT NULL,
    recorded_role VARCHAR(50) NOT NULL,
    recorded_at DATETIME(6) NOT NULL,
    transcription_status VARCHAR(20) NOT NULL,
    detected_language VARCHAR(30) NULL,
    original_transcript TEXT NULL,
    cleaned_transcript TEXT NULL,
    transcription_attempts INT NOT NULL DEFAULT 0,
    transcription_error VARCHAR(1000) NULL,
    last_attempt_at DATETIME(6) NULL,
    transcribed_at DATETIME(6) NULL,
    approved_text TEXT NULL,
    needs_review BIT(1) NOT NULL DEFAULT b'0',
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_voice_remark_actor_request (recorded_by, request_id),
    KEY idx_voice_remark_reference (reference_type, reference_id),
    KEY idx_voice_remark_queue (transcription_status, transcription_attempts, last_attempt_at)
);
